hpi-schul-cloud/end-to-end-tests

runtime/imageCompare.js
This handles different screenshot comparison timings. Note that the step itself still fails, cause the calendar data is different ton different days ... working on that ..
=> Handle different test timings

page-objects/administration.js
=> createNewPupil verification function adjusted

page-objects/news.js, shared-objects/loginData.js, shared_steps/firstLogin.js
https://github.com/schul-cloud/nuxt-client/pull/353
=> Nuxt (VUE-22) news create and edit

page-objects/homework.js
needed to adapt selector
https://github.com/schul-cloud/schulcloud-client/pull/1558
=> SC-3093 Homework File Uploader

features/createTeam.feature, page-objects/administration.js, shared-objects/administrationData.js, step_definitions/createTeam-steps.js
Reverts schul-cloud/integration-tests#57
=> Revert "feature/new admin routes"

features/homework.feature, package-lock.json, page-objects/homework.js, runtime/helpers.js, step_definitions/homework-steps.js
Feature test for the file upload.
Client: https://github.com/schul-cloud/schulcloud-client/pull/1780
Server: https://github.com/schul-cloud/schulcloud-server/pull/1228
=> [#SC-4064] Aufgaben feedback mit files erweitern (1/4)

page-objects/homework.js
Needed to adapt selectors
- https://github.com/schul-cloud/schulcloud-client/pull/1786
- https://ticketsystem.schul-cloud.org/browse/SC-4093
=> Changed path to task name

page-objects/editProfile.js, shared-objects/loginData.js, shared_steps/firstLogin.js
Ticket: https://ticketsystem.schul-cloud.org/browse/SC-4135
Client: schul-cloud/schulcloud-client#1828
=> SC-4250 - Adjustments for new front page

page-objects/createCourse.js
https://github.com/schul-cloud/schulcloud-client/pull/1796
=> fixed test for @createSimpleHomework

index.js, runtime/logger.js, runtime/world.js
Ich habe die Dateinamen der Reportdateien angepasst, so dass keine Leerzeichen mehr drin sind und dafür die Zeit hinzugefügt ist. So werden nun mehrere Reports des Tages vergleichbar. 
KlassiTech Automated TestReport-26-05-2020.html => KlassiTechAutomatedTestReport-26-05-2020-102239.html
=> filename without space but with timestamp

features/addPupilToTheCourse.feature, features/copyCourse.feature, features/homework.feature
Base links to copy
- https://github.com/schul-cloud/schulcloud-server/pull/1941
- https://ticketsystem.schul-cloud.org/browse/SC-5139
=> comment out failing tests

features/visibilityOfDialoguesTabsForTheAdmin.feature, page-objects/administration.js, shared-objects/administrationData.js, shared-objects/loginData.js, step_definitions/visibilityOfDialoguesTabsForTheAdmin.js
=> create new test sc-4993, administration are visibility for admin

CHANGELOG.md
https://github.com/schul-cloud/schulcloud-client/pull/1796
=> added information to CHANGELOG.md regarding @createSimpleHomework

features/visibilityOfDialoguesTabsForTheTeacher.feature, step_definitions/visibilityOfDialoguesTabsForTheTeacher-steps.js
=> create new test sc-5051, verwaltung are visibility for teacher

.github/workflows/update_version.yml
https://ticketsystem.schul-cloud.org/browse/OPS-737
Details are in the ticket
The filter was checked in the repository https://github.com/dimapin/github-actions-playground
=> OPS-737 Fixed the filter logic on create trigger

CHANGELOG.md, features/adminCreateClassWithoutParticipants.feature, page-objects/administration.js, shared-objects/administrationData.js, step_definitions/adminCreateClassWithoutParticipants-steps.js
previous branch was closed due to name change
Ticket:
https://ticketsystem.schul-cloud.org/browse/SC-4994
https://github.com/schul-cloud/schulcloud-client/pull/1975
depends on this client pr with same branch name
=> new branch from pull 83

package-lock.json, package.json, page-objects/createCourse.js
- fixes the missing dependency on axios which led to silently failing tests (e.g. https://travis-ci.com/github/schul-cloud/integration-tests/builds/173643309)
=> Add dependency on axios

page-objects/copyCourse.js, page-objects/createTask.js, page-objects/homework.js
Reverts schul-cloud/integration-tests#99
=> Revert "SC-4673 CKEditor update"

page-objects/pages/NWSAddEditNewsPage.js, runtime/helpers/dateTimeHelpers.js, step_definitions/news-steps.js
https://github.com/hpi-schul-cloud/nuxt-client/pull/1165
https://ticketsystem.schul-cloud.org/browse/SC-5758
=> bugfix - news not published later

step_definitions/adminCrossSchoolPermission-steps.js
Issue with ```UnhandledPromiseRejectionWarning: Error: Cannot find module '../page-objects/pages/loginPage'```
is now fixed. A missing foldername has now been added to a module import
=> add fix for misleading paths

features/administration.feature
Temporary ignore a test case as it caused an issue for the other test cases.
```ERROR webdriver: Request failed due to invalid session id``` was thrown when the following test case started.
=> ignore administration.feature

page-objects/copyCourse.js
Updated the name of the new settings icon
- https://ticketsystem.schul-cloud.org/browse/SC-5742
Updated the name of the new settings icon in page-objects - copyCourse
=> SC-5742 - replaced the settings icons

page-objects/administration.js
=> fix hardcoded id

page-objects/homework.js, page-objects/pages/HMWRKAddEditHomeworkPage.js, page-objects/pages/HMWRKHomeworkListPage.js
New selectors for changes in the HTML structure due to a11y issues 
https://ticketsystem.schul-cloud.org/browse/SC-5915
https://github.com/hpi-schul-cloud/schulcloud-client/pull/2052
=> SC-5915: homework dashboard

runtime/helpers/waitHelpers.js
add methods to wait helper
https://ticketsystem.schul-cloud.org/browse/SC-5796
=> SC-5796 add methods to wait helper

features/homework.feature, page-objects/pages/HMWRKAddEditHomeworkPage.js, page-objects/pages/HMWRKHomeworkListPage.js, step_definitions/homework-steps.js
extend and adjust
https://ticketsystem.hpi-schul-cloud.org/browse/SC-5285
=> SC - 5285 teacher creates a private homework

CHANGELOG.md, page-objects/pages/generalPagesBeforeLogin/LoginPage.js
During the creation of the new release package one testcase failed because of a message that is expected to be german but was english instead. Within the login.feature the scenario
@wrongPasswordAdminLogin had the following error message:
✖ Then the login must fail # shared_steps/common-steps.js:48
AssertionError
+ expected - actual
-Login failed.
+Login fehlgeschlagen.
at Object.wrongLoginResult (/home/travis/build/hpi-schul-cloud/schulcloud-client/integration-tests/page-objects/pages/generalPagesBeforeLogin/LoginPage.js:102:75)
at runMicrotasks (<anonymous>)
at processTicksAndRejections (internal/process/task_queues.js:97:5)
The problem is caused by the detection and usage of the browser language on the login page.
https://ticketsystem.hpi-schul-cloud.org/browse/OPS-1205
Updated the …
=> OPS-1205 - Handle German and English message

features/course.feature, page-objects/pages/coursePages/CRSSCourseListPage.js, page-objects/pages/coursePages/CRSSEditCopyCoursePage.js, page-objects/pages/coursePages/CRSSGeneralCoursePage.js, step_definitions/course-steps.js
create new test @editCourse
https://ticketsystem.hpi-schul-cloud.org/browse/SC-5169
=> SC - 4788 - edit a course

features/login.feature, package-lock.json, page-objects/pages/DashboardPage.js, step_definitions/login-steps.js
extend test @teacherLogin
https://ticketsystem.hpi-schul-cloud.org/browse/SC-5284
=> SC-5284 - extend test @teacherLogin

jsconfig.json, package-lock.json, package.json
A package that allows driver to show suggestions with intellisense (only tested with vs code).
For more information: see
https://webdriver.io/docs/autocompletion.html
You can now do this:
=> Add package that allows intellisense to list suggestions for driver

jsconfig.json, package-lock.json, package.json
Reverts hpi-schul-cloud/integration-tests#163
Reverting because Python needed to make the packages work
=> Revert "Add package that allows intellisense to list suggestions for driver"

page-objects/pages/DashboardPage.js, page-objects/pages/HMWRKAddEditHomeworkPage.js, page-objects/pages/HMWRKHomeworkListPage.js, page-objects/pages/HMWRKHomeworkPage.js, page-objects/pages/NWSAddEditNewsPage.js, page-objects/pages/NWSNewsListPage.js, page-objects/pages/NavigationTopPage.js, page-objects/pages/administrationPages/ADMNSTRTNAdministerClassesPage.js, page-objects/pages/administrationPages/ADMNSTRTNAdministerStudentsPage.js, page-objects/pages/administrationPages/ADMNSTRTNAdministrationOverviewPage.js, page-objects/pages/coursePages/CRSSAddCoursePage.js, page-objects/pages/coursePages/CRSSCourseGroupsPage.js, page-objects/pages/coursePages/CRSSCourseHomeworksPage.js, page-objects/pages/coursePages/CRSSCourseListPage.js, page-objects/pages/coursePages/CRSSCourseToolsPage.js, page-objects/pages/coursePages/CRSSCourseTopicsPage.js, page-objects/pages/coursePages/CRSSEditCopyCoursePage.js, page-objects/pages/coursePages/CRSSGeneralCoursePage.js, page-objects/pages/generalPagesBeforeLogin/LoginPage.js, page-objects/pages/generalPagesBeforeLogin/StartPageBeforeLogin.js, page-objects/pages/teamsPages/TMSTeamListPage.js, runtime/helpers/waitHelpers.js, shared_steps/common-steps.js, step_definitions/copyCourse-steps.js, step_definitions/searchCourse-steps.js, step_definitions/visibilityOfAdministrationTabsForAdmin-steps.js, step_definitions/visibilityOfDialoguesTabsForTheTeacher-steps.js
Moving selectors above module.exports
https://ticketsystem.hpi-schul-cloud.org/browse/SC-6900
=> Moving selectors above module.exports

features/course.feature, page-objects/pages/coursePages/CRSSCourseListPage.js, page-objects/pages/coursePages/CRSSEditCopyCoursePage.js, step_definitions/course-steps.js
create new test @deleteCourse
https://ticketsystem.hpi-schul-cloud.org/browse/SC-6821
refactor CRSSCourseListPage.js
=> SC - 6821 - delete course

CHANGELOG.md, features/copyCourse.feature, package-lock.json, package.json
- https://github.com/hpi-schul-cloud/schulcloud-client/pull/2228
- https://ticketsystem.schul-cloud.org/browse/SC-6945
- https://ticketsystem.hpi-schul-cloud.org/browse/SC-6990 ( mark as release blocker for 25.2.0 )
=> hotfix/3/skip @copyCourseWithText

features/course.feature, runtime/world.js
create posisbility to not reset DB before some scenarios
https://ticketsystem.hpi-schul-cloud.org/browse/SC-6653
=> SC - 6653 - implement possibility to not delete db before scenario

page-objects/pages/coursePages/CRSSAddCoursePage.js, runtime/helpers/elementHelpers.js
Chosen library is no longer used for dropdowns and selects due to accessibility issues. We should be using the native HTML elements instead.
The PR for the old client is: https://github.com/hpi-schul-cloud/schulcloud-client/pull/2209
The methods for testing dropdowns/selects changed, chosen selectors are replaced, the method for testing that no element was selected is changed.
=> SC-5858: chosen library removed

page-objects/pages/coursePages/CRSSAddCoursePage.js, runtime/helpers/elementHelpers.js
Reverts hpi-schul-cloud/integration-tests#192
=> Revert "SC-5858: chosen library removed"

.github/workflows/test.yml
add test runner in github flow
https://ticketsystem.hpi-schul-cloud.org/browse/OPS-1343
=> gitflow-feature-stash: add_tests_in_github

features/course.feature, page-objects/pages/coursePages/CRSSAddCoursePage.js, page-objects/pages/coursePages/CRSSCourseListPage.js, page-objects/pages/generalPagesBeforeLogin/LoginPage.js, runtime/helpers/APIhelpers.js, runtime/helpers/assertHelpers.js, runtime/helpers/axiosHelper.js, runtime/helpers/dateTimeHelpers.js, runtime/helpers/elementHelpers.js, runtime/helpers/filterHelpers.js, runtime/helpers/imageHelpers.js, runtime/helpers/numberHelpers.js, runtime/helpers/textFileHelpers.js, runtime/helpers/waitHelpers.js, shared_steps/common-steps.js, step_definitions/course-steps.js, step_definitions/versions.js
switch to use waitHelpers: helpers
https://ticketsystem.hpi-schul-cloud.org/browse/SC-7160
switch to use waitHelpers: helpers
Adaptation of methods to the new drop-downs version SC-5858, SC-7152
=> refactoring part 1

page-objects/pages/HMWRKAddEditHomeworkPage.js, page-objects/pages/HMWRKHomeworkListPage.js, page-objects/pages/NWSNewsListPage.js, page-objects/pages/coursePages/CRSSAddCoursePage.js, page-objects/pages/coursePages/CRSSCourseListPage.js, page-objects/pages/coursePages/CRSSEditCopyCoursePage.js, page-objects/pages/teamsPages/TMSTeamListPage.js, shared_steps/common-steps.js, step_definitions/copyCourse-steps.js, step_definitions/course-steps.js, step_definitions/createTask-steps.js, step_definitions/editTask-steps.js, step_definitions/homework-steps.js
https://ticketsystem.hpi-schul-cloud.org/browse/SC-6663
This PR aims to simplify some existing methods and remove duplicates within the pages. Removing redundancy within cucumber files is done in a different ticket (SC-6650)
What has been changed? 
/coursePages 
- AddCoursePage -> combined createCourse and createCourseWithStudents to one method	     
- CourseListPage -> combined isCourseVisible and isCourseNotVisible to one method 	     
- EditCopyCoursePage -> created setTextOfTextbox to reduce redundancy of setting name and description
/homework
- AddEditHomeWorkPage -> combined addBasicHometask and addPrivateHometask into addHomework to avoid redundant steps
- HomeworkListPage -> combined isTaskVisible and isTaskNotVisible into one method
/news
- NWSNewsListPage -> combined …
=> simplified methods and removed redundancy

features/login.feature, page-objects/apiTest.js, page-objects/pages/NWSAddEditNewsPage.js, page-objects/pages/NWSNewsListPage.js, page-objects/pages/NavigationBottomPage.js, page-objects/pages/NavigationLeftPage.js, page-objects/pages/NavigationTopPage.js, page-objects/pages/administrationPages/ADMNSTRTNAdministerStudentsPage.js, runtime/helpers/APIhelpers.js, runtime/helpers/elementHelpers.js, runtime/helpers/waitHelpers.js, step_definitions/copyCourse-steps.js, step_definitions/news-steps.js
switch to use waitHelpers: Learnstore, Meessanger, Nav, News Pages
https://ticketsystem.hpi-schul-cloud.org/browse/SC-6938
Methods from waitHelpers library to Learnstore, Meessanger, Nav, News Pages were applied
Removed outdated and incorrectly written methods/tests/steps
=> switch to use waitHelpers Learnstore, Meessanger, Nav, News Pages

features/copyCourse.feature, page-objects/pages/coursePages/CRSSAddEditTopicPage.js, step_definitions/copyCourse-steps.js
=> Sc 6990 repair scenario @copy course with text

CHANGELOG.md, features/administration.feature, features/copyCourse.feature, features/course.feature, features/createClassWithoutParticipants.feature, features/createTask.feature, features/createTeam.feature, features/crossSchoolPermission.feature, features/editClass.feature, features/editTask.feature, features/navigationLeft.feature, features/news.feature, features/searchCourse.feature, features/task.feature, features/topic.feature, features/versions.feature, features/visibilityOfMenuItems.feature, page-objects/pages/DashboardPage.js, page-objects/pages/coursePages/CRSSAddCoursePage.js, page-objects/pages/coursePages/CRSSCourseListPage.js, page-objects/pages/teamsPages/TMSAddEditTeamPage.js, page-objects/pages/teamsPages/TMSTeamListPage.js, runtime/helpers/waitHelpers.js, step_definitions/administartion-steps.js, step_definitions/course-steps.js, step_definitions/createClassWithoutParticipants-steps.js, step_definitions/createTeam-steps.js, step_definitions/task-steps.js, step_definitions/topic-steps.js
teams, topics, class steps - improve terms in cucumber steps
https://ticketsystem.hpi-schul-cloud.org/browse/SC-7110
teams, topics, class steps - improve terms in cucumber steps
=> teams, topics, class steps - improve terms in cucumber steps

CHANGELOG.md, features/sendConsentFormEmail.feature, step_definitions/sendConsentFormEmail-steps.js
Adjusted sendConsentFormEmail.feature due to functional changes - introduced with SC-7571
https://ticketsystem.hpi-schul-cloud.org/browse/SC-7571
=> SC-7571 adjusted sendConsentFormEmail due to functional change

CHANGELOG.md, features/administration.feature, page-objects/pages/administrationPages/ADMNSTRTNAdministerTeachersPage.js, page-objects/pages/administrationPages/ADMNSTRTNAdministrationOverviewPage.js, page-objects/pages/administrationPages/ADMNSTRTNEditDeleteTeacherPage.js, step_definitions/administartion-steps.js
deleted users can not login anymore
https://ticketsystem.hpi-schul-cloud.org/browse/SC-7733
=> SC-7733 - user can't login anymore

features/searchCourse.feature, page-objects/pages/coursePages/CRSSCourseListPage.js, step_definitions/searchCourse-steps.js
- made some small changes to @searchCourse feature
- added/exchanged new users that are stored in the db
- removed unnecessary steps like an additional call to goToCoursePage
- https://github.com/hpi-schul-cloud/end-to-end-tests/pull/239
- https://ticketsystem.hpi-schul-cloud.org/browse/SC-7209
- added/exchanged new users that are stored in the db
- removed unnecessary steps like an additional call to goToCoursePage
nn
nn
=> added new users and removed unnecessary steps

features/copyCourse.feature, features/course.feature, features/createTask.feature, features/createTeam.feature, features/dashboard.feature, features/editTask.feature, features/news.feature, features/task.feature, features/topic.feature, features/visibilityOfMenuItems.feature, index.js, page-objects/pages/NWSNewsListPage.js, page-objects/pages/TASKAddEditTaskPage.js, page-objects/pages/TASKListPage.js, page-objects/pages/TASKPage.js, page-objects/pages/coursePages/CRSSAddCoursePage.js, page-objects/pages/coursePages/CRSSCourseHomeworksPage.js, page-objects/pages/coursePages/CRSSCourseListPage.js, page-objects/pages/coursePages/CRSSGeneralCoursePage.js, runtime/helpers/dateTimeHelpers.js, runtime/helpers/tableHelpers.js, runtime/world.js, shared_steps/common-steps.js, step_definitions/course-steps.js, step_definitions/createTask-steps.js, step_definitions/createTeam-steps.js, step_definitions/dashboard-steps.js, step_definitions/editTask-steps.js, step_definitions/news-steps.js, step_definitions/task-steps.js
improve terms in cucumber steps - tasks
https://ticketsystem.hpi-schul-cloud.org/browse/SC-7111
improve terms in cucumber steps - tasks
new methods dateTimeHelpers, tableHelpers
=> improve terms in cucumber steps - tasks

CHANGELOG.md, features/management_students/createStudent.feature, page-objects/pages/managementPages/ManageStudentsPage.js, step_definitions/management_students/createStudent_steps.js
As a admin, I want to invite a student to the sc plattform so that the student can register himself. 
https://ticketsystem.hpi-schul-cloud.org/browse/SC-5795
Add test for checking if registration link is sent 
=> SC-5795-Admin creates user and sends registration link

CHANGELOG.md, features/management_classes/deleteClass.feature, page-objects/pages/managementPages/ManageClassPage.js, page-objects/pages/managementPages/ManageStudentPage.js, step_definitions/management_classes/deleteClass_steps.js, step_definitions/management_classes/editClass_steps.js
As a teacher I want to delete a class I don't need anymore
- https://ticketsystem.hpi-schul-cloud.org/browse/SC-6814
=> SC-6814 - deleting class

CHANGELOG.md, page-objects/pages/HMWRKAddEditHomeworkPage.js, page-objects/pages/coursePages/CRSSAddCoursePage.js, page-objects/pages/teamsPages/TMSTeamMembersPage.js, step_definitions/course-steps.js
fixed failing tests
https://ticketsystem.hpi-schul-cloud.org/browse/SC-7878
=> Hotfix/1/SC-7878 - fixed failing tests 

CHANGELOG.md, features/management_classes/editClass.feature, features/management_students/deleteStudent.feature, features/teams/createTeam.feature, features/teams/editTeam.feature, page-objects/pages/DashboardPage.js, page-objects/pages/teamsPages/TMSAddEditTeamPage.js, page-objects/pages/teamsPages/TMSGeneralTeamPage.js, page-objects/pages/teamsPages/TMSTeamListPage.js, page-objects/pages/teamsPages/TMSTeamMembersPage.js, step_definitions/courses/editCourse_steps.js, step_definitions/teams/createTeam_steps.js, step_definitions/teams/editTeam_steps copy.js
create new test
https://ticketsystem.hpi-schul-cloud.org/browse/SC-5780
=> SC - 5780 - teacher edits team

CHANGELOG.md, features/management_classes/editClass.feature, page-objects/pages/managementPages/ManageClassPage.js, page-objects/pages/managementPages/ManageClassesPage.js, step_definitions/management_classes/createClass_steps.js, step_definitions/management_classes/editClass_steps.js
crete new test editClass
https://ticketsystem.hpi-schul-cloud.org/browse/SC-6816
=> SC - 6816 - new test @editClass

package-lock.json, package.json, scripts/ci/end-to-end-tests.github.sh
=> print it client envs

CHANGELOG.md, features/management_classes/editClass.feature, features/management_students/deleteStudent.feature, features/teams/createTeam.feature, page-objects/pages/AccountPage.js, page-objects/pages/NWSNewsListPage.js, page-objects/pages/TASKAddEditTaskPage.js, page-objects/pages/coursePages/CRSSAddCoursePage.js, page-objects/pages/managementPages/ManageClassPage.js, page-objects/pages/managementPages/ManageCoursesPage.js, page-objects/pages/teamsPages/TMSTeamMembersPage.js, runtime/helpers/elementHelpers.js, step_definitions/management_classes/createClass_steps.js, step_definitions/management_classes/editClass_steps.js, step_definitions/teams/createTeam_steps.js
New test: addGroupOfStudentsToTheClass
https://ticketsystem.hpi-schul-cloud.org/browse/SC-5286
-Created a new test: addGroupOfStudentsToTheClass
- selectOptionsByText(selectSelector, option) improved to selectOptionsByText(selectSelector, options)
=> new test: addGroupOfStudentsToTheClass

CHANGELOG.md, features/management_classes/createClass.feature, page-objects/pages/TASKPage.js, page-objects/pages/managementPages/ManageClassesPage.js, runtime/helpers/tableHelpers.js, step_definitions/management_classes/createClass_steps.js
create new test @createClassWith3Members
https://ticketsystem.hpi-schul-cloud.org/browse/SC-8120
=> SC - 8120 - create new test createClassWith3Members

CHANGELOG.md, features/user_settings/changeLanguageMenu.feature, page-objects/pages/AccountPage.js, step_definitions/user_settings/changeLanguageMenu_steps.js
created because of changes in https://github.com/hpi-schul-cloud/schulcloud-client/pull/2404/
- https://github.com/hpi-schul-cloud/schulcloud-client/pull/2404/
- https://ticketsystem.hpi-schul-cloud.org/browse/SC-7848
added fillPassword function in settings
=> SC-7848 - fix to fill current password due to new client bugfix

CHANGELOG.md, features/user_settings/changeLanguageMenu.feature
Change lern-store to Learning Store.
Related to this client side pr:
https://github.com/hpi-schul-cloud/schulcloud-client/pull/2415
=> Change name of expected menuitems

.github/workflows/test.yml, CHANGELOG.md, scripts/ci/end-to-end-tests.github.sh, scripts/ci/end-to-end-tests.travis.sh
This PR introduces authentication against docker hub to avoid running into limitations.
=> SC-8356 add docker authentication against pull limitation

page-objects/pages/NavigationLeftPage.js, runtime/helpers/elementHelpers.js
i rebased my recent changes to be merged as normal into develop:
- fix helper get link selector
- use loadpage to check navigation item links
=> SC-8321 await left navigation items with children are loaded

CHANGELOG.md, features/management_students/createStudent.feature
- extended the test case createNewStudentU14 so that it also performs first login steps
- https://github.com/hpi-schul-cloud/end-to-end-tests/pull/281
- https://ticketsystem.hpi-schul-cloud.org/browse/SC-8122
- extended the test case createNewStudentU14 by a few steps
nn
nn
=> extended test steps to fullfil firstLogin steps for student u14

CHANGELOG.md, page-objects/apiTest.js
According to the error handling concept [link](https://docs.hpi-schul-cloud.org/display/TSC/Error+Handling+Guildelines#ErrorHandlingGuildelines-ErrorsintheServer) the error message response should be adjusted in a way it does always contains a set of predefined properties including: code, message, type and title.
Therefore it was necessary to rename the err.name property to err.title.
https://ticketsystem.hpi-schul-cloud.org/browse/SC-8213
=> SC-8213 error handling - response format

features/management_classes/editClass.feature, features/management_teachers/deleteTeacher.feature, features/navigation_bar_left/leftNavigationBar.feature, features/user_settings/changeLanguageMenu.feature, page-objects/pages/NavigationLeftPage.js, page-objects/pages/managementPages/ManageClassesPage.js
- fixed/updated test cases due to localisation changes
- Lehrer was renamed to Lehrkraft
- Schüler:inn(en) was added in some more cases
- Administrator was renamed to Admin
- https://github.com/hpi-schul-cloud/schulcloud-client/pull/2397
- https://github.com/hpi-schul-cloud/end-to-end-tests/pull/276/
- https://ticketsystem.hpi-schul-cloud.org/browse/SC-8318
- fixed/updated test cases due to localisation changes
nn
nn
=> Lokalise 2020 12 11 07 33 00

features/management_classes/createClass.feature
Within https://github.com/hpi-schul-cloud/end-to-end-tests/pull/299 we accidentally removed a test step although it was still used. I exchanged the removed test step to an existing one.
=> exchanged removed test step to existing one

.travis.yml, CHANGELOG.md, scripts/ci/end-to-end-tests.github.sh, scripts/ci/end-to-end-tests.travis.sh
=> fix fallbacks

CHANGELOG.md, features/management_students/createStudent.feature, page-objects/pages/managementPages/ManageStudentsPage.js
Since the tests with emails are often failing due to instabilities in the process of sending mails we are disabling the tests now. The functionality of sending emails is tested manually anyway so this is, for now, not a big problem. 
When the notification service / mail problems have been 'fixed' we may reintroduce these tests. 
Disable Email tests
=> disable email tests

features/courses/copyCourse.feature, features/user_settings/changeLanguageMenu.feature
Updated the test changeLanguageMenu.feature to make it work again with latest changes by feature team odyssey which introduced the task dashboard for teachers.
=> Updated the tests to run with latest changes

features/management_classes/createClass.feature, features/management_students/deleteStudent.feature, features/management_teachers/deleteTeacher.feature
Due to the schoolyear change from 2020/21 t 2021/22 some test that use the school year hard coded were failing. This was fixed.
=> changed hard coded school year

package-lock.json, package.json
=> Update selenium-standalone 6.16.0 -> 6.24.0

package-lock.json, package.json
=> Update winston 3.2.1 -> 3.3.3

package-lock.json, package.json, page-objects/pages/coursePages/CRSSAddCoursePage.js, page-objects/pages/coursePages/CRSSAddEditTopicPage.js, runtime/browserStackDriver.js, runtime/chromeDriver.js, runtime/firefoxDriver.js, runtime/helpers/waitHelpers.js, step_definitions/courses/createCourse_steps.js
=> Major dependency updates

index.js, package-lock.json, package.json
=> Second major dependency updates

CHANGELOG.md, scripts/ci/end-to-end-tests.github.sh
Added a line to reinstate that all E2E tests are running within every PR.
=> reinstated that all tests are running

.github/workflows/test.yml, scripts/ci/end-to-end-tests.github.sh, scripts/ci/fetch.github.sh
Set BRANCH_NAME do the test run correctly
https://ticketsystem.hpi-schul-cloud.org/browse/BC-66
https://ticketsystem.hpi-schul-cloud.org/browse/BC-64
Set BRANCH_NAME do the test run correctly
=> BC-66 - Fix e2e test 

CHANGELOG.md, page-objects/pages/managementPages/ManageStudentsPage.js, step_definitions/management_students/createStudent_steps.js
=> fix createStudent scenario 

CHANGELOG.md, page-objects/pages/TASKListPage.js, step_definitions/management_students/editStudent_steps.js
The e2e test @sendConsentFormEmail is unstable and within this PR we are trying to get it more stable.
- https://ticketsystem.hpi-schul-cloud.org/browse/BC-283
=> BC-283 exchanged a waiting method

CHANGELOG.md, features/courses/createCourse.feature, features/courses/editCourse.feature, page-objects/pages/coursePages/CRSSCourseListPage.js
=> fix course colours

CHANGELOG.md, scripts/ci/end-to-end-tests.github.sh
=> hide docker log to reduce output

.github/workflows/e2e.yml, .github/workflows/e2e_call.yml, CHANGELOG.md
Update e2e test so there is an new workflow to call by other repos
https://ticketsystem.hpi-schul-cloud.org/browse/BC-402
Update e2e test so there is an new workflow to call by other repos
=> BC-402 - Update e2e test so there is an new workflow to call by other repos

CHANGELOG.md, page-objects/pages/TASKPage.js
=> BC-155 - tab renamed

CHANGELOG.md, features/management_students/deleteStudent.feature, features/teams/createTeam.feature, page-objects/pages/TASKListPage.js, page-objects/pages/teamsPages/TMSTeamListPage.js
Update the deleteTask.feature as it did not wait for the task to delete and fails and the very next step. Even though the task was deleted. Actually failed in this PR:
https://github.com/hpi-schul-cloud/schulcloud-server/runs/4459330402?check_suite_focus=true
https://ticketsystem.hpi-schul-cloud.org/browse/BC-826
=> Browser loading issue

features/tasks/deleteTask.feature, features/tasks/editTask.feature, features/tasks/gradeTask.feature
The test @teacherGradesAndViewsTask in gradeTask.feature is unstable, therefore I marked it as unstable.
Ticket: https://ticketsystem.hpi-schul-cloud.org/browse/BC-1075
PR: https://github.com/hpi-schul-cloud/schulcloud-client/pull/2745
=> marked test as unstable

features/management_students/editStudent.feature, features/tasks/deleteTask.feature, features/tasks/editTask.feature, features/tasks/gradeTask.feature, features/tasks/submitTask.feature
The tags are not exclusive, but only inclusive.
Therefor, unstable tests should not have '@unstableTest' marking at the same time with the marking of the group like '@tasks_and_other' (at the leefl of the test of the feature).
- https://ticketsystem.hpi-schul-cloud.org/browse/BC-1100
=> BC-1100 - remove wrong tagging

features/dashboard/task.feature, features/tasks/deleteTask.feature, features/tasks/editTask.feature, features/tasks/gradeTask.feature, features/tasks/submitTask.feature, page-objects/pages/TASKListPage.js, page-objects/pages/TASKPage.js, runtime/helpers/elementHelpers.js
Test cases from taskoverview are mostly failing in CI/CD. Problem is that most of the time when test fails in CI/CD screenshot does not shows the correct task in the screen. So we don't know that either the task is in the viewport or not. In this PR, introduce scroll into task function also some wait to exactly capture the task which we want to test.
=> Refactor task scenarios

features/dashboard/task.feature, features/tasks/deleteTask.feature, features/tasks/editTask.feature, features/tasks/gradeTask.feature, page-objects/pages/TASKListPage.js, page-objects/pages/TASKPage.js, runtime/helpers/waitHelpers.js, step_definitions/tasks/createTask_steps.js, step_definitions/tasks/gradeTask_steps.js, step_definitions/tasks/submitTask_steps.js
Refactor required after the merge of BC-643.
https://ticketsystem.hpi-schul-cloud.org/browse/BC-1008
=> BC-1008-Refactor e2e tests after merge of BC-643

package-lock.json
created from depedendabot - branch renamed so that tests run
=> Npm and yarn/follow redirects 1.14.7

package-lock.json
created from depedendabot - branch renamed so that tests run
=> Bump follow-redirects from 1.14.7 to 1.14.8

features/tasks/editTask.feature, features/tasks/gradeTask.feature, page-objects/pages/TASKListPage.js, page-objects/pages/TASKPage.js, runtime/chromeDriver.js, runtime/helpers/elementHelpers.js, runtime/helpers/waitHelpers.js, step_definitions/tasks/gradeTask_steps.js
Refactor click at task step.
https://ticketsystem.hpi-schul-cloud.org/browse/BC-1085
=> BC-1085 click at task 

features/tasks/createTask.feature, features/tasks/editTask.feature, features/tasks/submitTask.feature, page-objects/pages/TASKListPage.js, page-objects/pages/TASKPage.js, step_definitions/tasks/createTask_steps.js, step_definitions/tasks/editTask_steps.js
Refactoring e2e tests
https://ticketsystem.hpi-schul-cloud.org/browse/BC-1214
=> BC-1214-refactor-e2e-tests

page-objects/pages/TASKListPage.js
=> BC-1407 - adjusted task-menu selector

features/courses_topics/editTopic.feature
Due to new behaviour for redirecting after lesson creation/editing the e2e test needs to be adjusted.
Ticket: https://ticketsystem.dbildungscloud.de/browse/BC-1607
Legacy Client PR: https://github.com/hpi-schul-cloud/schulcloud-client/pull/2820
Nuxt Client PR: https://github.com/hpi-schul-cloud/nuxt-client/pull/2127
=> BC-1607 - redirect after lesson creation

features/courses_topics/editTopic.feature
=> revert lesson redirect changes

package-lock.json, package.json
hpi-schul-cloud/schulcloud-server#3401
hpi-schul-cloud/schulcloud-client#2817
hpi-schul-cloud/nuxt-client#2122
hpi-schul-cloud/schulcloud-calendar#123
hpi-schul-cloud/dof_app_deploy#219
=> version 27.12.0

package-lock.json, package.json
https://github.com/hpi-schul-cloud/dof_app_deploy/pull/296
https://github.com/hpi-schul-cloud/schulcloud-server/pull/3527
https://github.com/hpi-schul-cloud/nuxt-client/pull/2219
https://github.com/hpi-schul-cloud/schulcloud-client/pull/2916
https://github.com/hpi-schul-cloud/end-to-end-tests/pull/420
=> version 28.4.0

scripts/ci/end-to-end-tests.github.sh
https://github.com/hpi-schul-cloud/schulcloud-server/pull/3554
https://github.com/hpi-schul-cloud/dof_app_deploy/pull/307
https://github.com/hpi-schul-cloud/end-to-end-tests/pull/423
=> BC-2078 change npx wait-on for server to /serverversion

features/management_classes/createClass.feature, features/management_classes/editClass.feature, features/management_students/deleteStudent.feature
Adjust seed backup data to new school year 22/23 for server and change e2e tests with it.
BC-2240
https://github.com/hpi-schul-cloud/schulcloud-server/pull/3578
=> BC-2240 - Adjust e2e tests for changed seed data after school year change to 2022/23

.github/workflows/e2e.yml, .github/workflows/e2e_call.yml
=> updated github actions

page-objects/pages/teamsPages/TMSAddEditTeamPage.js, page-objects/pages/teamsPages/TMSTeamListPage.js
Adapt legacy e2e tests to new data test ids
BC-2820
https://github.com/hpi-schul-cloud/schulcloud-client/pull/3035
https://github.com/hpi-schul-cloud/e2e-system-tests/pull/88
=> BC-2820 - [E2E: Teams]: Student manages teams (on BRB)

.github/workflows/e2e.yml, .github/workflows/e2e_call.yml, page-objects/pages/managementPages/ManageStudentsPage.js, runtime/helpers/waitHelpers.js, scripts/ci/end-to-end-tests.github.sh, shared-objects/servers.js
=> BC-2674 Nuxt removal

features/user_settings/changeLanguageMenu.feature
Now the sidebar items have the same titles in both clients.
Ticket: https://ticketsystem.dbildungscloud.de/browse/BC-3863
Vue Client: https://github.com/hpi-schul-cloud/nuxt-client/pull/2498
Legacy Client: https://github.com/hpi-schul-cloud/schulcloud-client/pull/3173
=> BC-3863 different naming items in sidebar navigation

page-objects/pages/RoomsOverviewPage.js
Now its possible to enter a course/room from the room overview/list page with a screen reader.
https://ticketsystem.dbildungscloud.de/browse/BC-4019
=> BC-4019 - Accessible navigation to room/course

page-objects/pages/AccountPage.js
https://ticketsystem.dbildungscloud.de/browse/BC-2762
- https://github.com/hpi-schul-cloud/dof_app_deploy/pull/526
- https://github.com/hpi-schul-cloud/schulcloud-server/pull/4139
- https://github.com/hpi-schul-cloud/schulcloud-client/pull/3199
- https://github.com/hpi-schul-cloud/nuxt-client/pull/2541
=> BC-2762 - adjust ukrainian language key

features/management_classes/createClass.feature, features/management_classes/editClass.feature, features/management_students/deleteStudent.feature
Adjust seed data to new school year 23/24 for server and e2e tests with it.
BC-4379
https://github.com/hpi-schul-cloud/schulcloud-server/pull/4284
=> BC-4379 - Adjust seed data to school year 2023/24 for backup in server

features/navigation_bar_left/leftNavigationBar.feature
=> temporarily disable contact page due to confluence being not reachable

page-objects/pages/NWSAddEditNewsPage.js, runtime/helpers/waitHelpers.js
As a step towards vue3 we remove tiptap usage in news section and change to CK5
https://ticketsystem.dbildungscloud.de/browse/BC-5863
https://github.com/hpi-schul-cloud/nuxt-client/pull/2926
https://github.com/hpi-schul-cloud/schulcloud-server/pull/4592
=> BC-5863 - remove tiptap

page-objects/pages/coursePages/CRSSCourseListPage.js
As result of internal changes of Vuetify3 we need to adapt our end-to-end-tests.
[BC-6643](https://ticketsystem.dbildungscloud.de/browse/BC-6643)
=> BC-6643 - fixing selector for course search input field

features/courses/searchCourse.feature, features/management_students/createStudent.feature, features/management_teachers/createTeacher.feature, features/navigation_bar_left/leftNavigationBar.feature, features/teams/deleteTeam.feature, features/teams/editTeam.feature, features/user_settings/changeLanguageMenu.feature, package-lock.json, package.json, page-objects/pages/AccountPage.js, page-objects/pages/coursePages/CRSSCourseListPage.js, page-objects/pages/managementPages/ManageStudentsPage.js, page-objects/pages/managementPages/ManageTeacherPage.js, runtime/helpers/waitHelpers.js, shared-objects/servers.js
Fixing some tests as selectors don't work anymore with the way vue3 handles data-testids.
- https://ticketsystem.dbildungscloud.de/browse/BC-3844
- https://ticketsystem.dbildungscloud.de/browse/BC-6643
=> BC-3844 - vue3 upgrade

scripts/ci/end-to-end-tests.github.sh
docker-compose -> docker compose
BC-7026
https://github.com/hpi-schul-cloud/docker-compose/pull/69
=> BC-7026 - fix docker compose command
